{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./clean.nix
    ./disk.nix
    ./gamemode.nix
    ./greeter.nix
    ./input.nix
    ./keyring.nix
    ./light.nix
    ./locale.nix
    ./network.nix
    ./nix.nix
    ./nvidia.nix
    ./powersave.nix
    ./support.nix
    ./users.nix
    ./zram.nix
  ];
}
