{marketplace}:
with marketplace; [
  angular.ng-template
  astro-build.astro-vscode
  activitywatch.aw-watcher-vscode
  biomejs.biome
  editorconfig.editorconfig
  emeryao.file-counter
  bierner.markdown-preview-github-styles
  bierner.markdown-emoji
  bierner.markdown-checkbox
  bierner.markdown-yaml-preamble
  bierner.markdown-footnotes
  bierner.markdown-mermaid
  ecmel.vscode-html-css
  davidanson.vscode-markdownlint
  unifiedjs.vscode-mdx
  misodee.vscode-nbt
  jnoortheen.nix-ide
  ziyasal.vscode-open-in-github
  slevesque.shader
  svelte.svelte-vscode
  minecraftcommands.syntax-mcfunction
  albert.tabout
  vitest.explorer
]
